repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-check
        args: [--fix]

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.16
    hooks:
      - id: vulture
        args: [src/, main]

  - repo: https://github.com/h8d13/cruft
    rev: 090c411b948961a73dba4d21d5f04e3822f9acb2
    hooks:
      - id: duper
