repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-check
        args: [--fix]

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.16
    hooks:
      - id: vulture
        args: [src/, main]

  - repo: https://github.com/h8d13/cruft
    rev: 15f91f01cce2e36a698eba5cb9da7e73d403130d
    hooks:
      - id: duper
